#!/bin/sh

alias cp="cp -i" \
dd="dd status=progress" \
flash="dd status=progress oflag=direct bs=1M" \
gr="git remote get-url origin | xargs $BROWSER" \
gf="git fetch" \
gp="git pull" \
grep="grep --color=auto" \
la="ls -alN" \
ls="ls --color=auto -hv --group-directories-first" \
make="make -j\$(nproc)" \
myip="curl ipinfo.io/ip" \
nb="newsboat" \
nc="ncmpcpp" \
p="pacman" \
rm="rm -I" \
s="$SUDO " \
unxz="unxz -v" \
v="nvim" \
ytdl="youtube-dl" \
clb="cd ~/.local/bin" \
cls="cd ~/.local/share" \
c3p="cd ~/3d/projects" \
