#!/bin/sh

# required by rofi for .desktop OnlyShowIn= support
export XDG_CURRENT_DESKTOP=dwm

# Background programs
dunst &
#~/bin/dwmblocks/dwmblocks &
#bar.sh &
#mpd_notify.sh &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#libinput-gestures-start

# Set settings
kb.sh
#nvidia-settings --load-config-only
xrdb -merge ~/.config/Xresources
xsetroot -solid "#111111"

exec dwm
