#!/bin/sh

# required by rofi for .desktop OnlyShowIn= support
export XDG_CURRENT_DESKTOP=dwm

# Background programs
dunst &
#~/bin/dwmblocks/dwmblocks &
#bar.sh &
#mpd_notify.sh &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#libinput-gestures-start

# Set settings
kb.sh
xrdb -merge ~/.config/Xresources
xsetroot -solid "#242933"

exec dwm
