#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "$(ps axch -o cmd,%cpu --sort -%cpu | sed 11q)" ;;
esac

load=$(cat /proc/loadavg | awk '{print $1}')

# FULL_TEXT
echo $load

# SHORT_TEXT
echo

# FOREGROUND COLOR
#if [ $(echo "$load>$(nproc)" | bc) -eq 1 ]; then	# If load is greater than the number of cpu cores
#	echo "$(xrdb -q | awk '/color9/ {print $2}')"
#else
#	echo "$(xrdb -q | awk '/color13/ {print $2}')"
#fi