#!/bin/sh

case $BLOCK_BUTTON in
	1) $TERMINAL -e sudo pacman -Syu ;;
	3) notify-send "$(pacman -Qu)" ;;
esac

echo -n $(pacman -Qu |grep "nvidia" | wc -l | awk '!/0/ {print "Restart required"}')

echo -e " $(pacman -Qu | wc -l | sed -e 's/^0$//g')"
