#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "$(ps axch -o cmd,%mem --sort -%mem | sed 11q)" ;;
esac

# FULL_TEXT
echo -e "$(free -h | awk '/Swap:/ && $3!="0B" {print $3" "}' | tr '\n' ' ' | head -c-1)"

# SHORT_TEXT
echo

# FOREGROUND COLOR
#echo "$(xrdb -q | awk '/color11/ {print $2}')"
