#!/bin/sh

case $BLOCK_BUTTON in
	2) amixer -q sset Master toggle ;;
	4) amixer -q sset Master 5%+ ;;
	5) amixer -q sset Master 5%- ;;
esac

volume=$(amixer sget Master | awk '/Front Left:/ {print substr($5,2)}' | sed 's/%.*//')
output=$(amixer sget Master | awk '/Front Left:/ {print substr($6,2)}' | sed 's/]//')

if [ $output = "off" ]; then
	echo -e "muted $volume%\n\n$(xrdb -q | awk '/color8/ {print $2}')"
else
	echo -n "VOL $volume%"
fi
