#!/bin/sh

DEST="$HOME/Asiakirjat/GitHub/dotfiles"

FILE[0]=".Xresources"
FILE[1]=".bashrc"
FILE[2]=".profile"
FILE[3]=".nanorc"
FILE[4]=".xinitrc"
FILE[5]=".config/i3/"
FILE[6]=".config/dunst/"
FILE[7]=".config/rofi/"
FILE[8]=".config/gtk-3.0/"
FILE[9]=".scripts/"
FILE[10]=".nanofiles/"
FILE[11]=".gtkrc-2.0"

for filename in "${FILE[@]}"; do
	rm -r "$DEST"/"$filename"
	cp -r "$HOME"/"$filename" "$DEST"/"$filename"
done
