#!/bin/bash

DEST="$HOME/Asiakirjat/GitHub/dotfiles"

FILE[0]=".Xresources"
FILE[1]=".bashrc"
FILE[2]=".profile"
FILE[3]=".xinitrc"
FILE[5]=".config/dunst/"
FILE[6]=".config/gtk-3.0/"
FILE[7]=".scripts/"
FILE[8]=".gtkrc-2.0"

for filename in "${FILE[@]}"; do
	rm -r "$DEST"/"$filename"
	cp -r "$HOME"/"$filename" "$DEST"/"$filename"
done
