#!/bin/sh

symbol=$(cat ~/.emoji | rofi -columns 2 -dmenu -p "Copy emoji to clipboard" | awk '{print $1}')

echo $symbol | xclip -selection primary
echo $symbol | xclip -selection clipboard
notify-send "$symbol copied to primary selction and clipboard"
