#!/bin/sh

symbol=$(cat ~/.emoji | rofi -columns 2 -dmenu -p "Copy emoji to clipboard" | awk '{printf $1}')

if [[ $symbol -eq "" ]]; then exit; fi;

echo -n $symbol | xclip -selection primary
echo -n $symbol | xclip -selection clipboard
notify-send "$symbol copied to primary selction and clipboard"
