#!/bin/bash

while [ 1 ];
do
lscpu | awk '/CPU MHz/ {print "CPU: ", $3 "MHz"}'
sensors |awk '/CPUTIN/ {print "CPU temp: ", $2}'

sensors |awk '/temp1:/ {print "temp1: ", $2}'
sensors |awk '/fan2:/ {print "fan2: ", $2 "rpm"}'

nvidia-smi -q -d utilization |awk '/Gpu/ {print "Gpu usage: ", $3 "%"}'

printf "\033[A\033[A\033[A\033[A\033[A"
sleep 0.1
done
