#!/bin/sh
export WINEPREFIX="$HOME/.wine_osu"
export WINEARCH=win32
export STAGING_AUDIO_DURATION=5000 # As low as you can get osu! stable with

# Arch Linux/wine-osu users should uncomment next line
# for the patch to be effective
export PATH=/opt/wine-osu/bin:$PATH

cd "/home/riku/.wine_osu/drive_c/osu"	#osu installation directory
env __GL_SYNC_TO_VBLANK=0 wine osu!.exe "$@"	#start osu with vsync off

