#!/bin/sh

if [ -z $(xsetwacom list devices) ]; then
	notify-send "Tablet was not detected"
	exit
fi

DEVICE="Wacom Intuos S"

STYLUS="$DEVICE Pen stylus"
ERASER="$DEVICE Pen eraser"
PAD="$DEVICE Pad pad"

## Stylus
if [ $(xsetwacom get "$STYLUS" Suppress) == 2 ]; then
	notify-send "Setting tablet to pefromance mode"
	xsetwacom set "$STYLUS" Suppress 1
	xsetwacom set "$STYLUS" RawSample 1
else
	notify-send "Setting tablet to quality mode"
	xsetwacom set "$STYLUS" Suppress 2
	xsetwacom set "$STYLUS" RawSample 4
fi
## Eraser

## Pad
#xsetwacom set "$PAD" Button 1 "key shift ctrl n"  # New layer
#xsetwacom set "$PAD" Button 2 "key p"  # Paintbrush
#xsetwacom set "$PAD" AbsWheelDown "key minus"  # Zoom out
#xsetwacom set "$PAD" AbsWheelUp "key shift plus"  # Zoom in
#xsetwacom set "$PAD" Button 3 "key a"  # Airbrush
#xsetwacom set "$PAD" Button 4 "key control z"  # Undo

